// SPDX-License-Identifier: MIT

pragma solidity 0.8.11;

import "@openzeppelin/contracts/access/Ownable.sol";  // OZ STANDARD
import "@openzeppelin/contracts/utils/Strings.sol";   // OZ STANDARD
import "./base/ERC721A.sol";                          // ERC721

/**
 * @title InvadERCore
 * @notice Produced by @InvaderETH for [ X ]. 
 * @dev Generated by the InvaderSuite [ X ].
**/ 

contract InvaderCore is Ownable, ERC721A {
  uint256 public burnedTokens;

  struct SaleConfig {
    uint256 tokenMax;
    uint256 tokenCap;
    uint256 tokenBatch;
    uint256 tokenReserve;
  }

  SaleConfig public config = SaleConfig;

  constructor() ERC721A("InvaderCore", "INVCORE", config.tokenBatch) {}
}