// SPDX-License-Identifier: MIT

pragma solidity 0.8.11;

import "@openzeppelin/contracts/access/Ownable.sol";  // OZ STANDARD
import "@openzeppelin/contracts/utils/Strings.sol";   // OZ STANDARD
import "./base/ERC721A.sol";                          // ERC721

/**
 * @title InvadERCore
 * @notice Produced by @InvaderETH for [ X ]. 
 * @dev Generated by the InvaderSuite [ X ].
**/ 

contract InvaderCore is Ownable, ERC721A {
  uint256 public immutable maxPerAddress;
  uint256 public immutable reservedTokens;
  uint256 public immutable burnedTokens;

  constructor() ERC721A("InvaderCore", "INVCORE", maxPerAddress) { }
}